### ISSUE TITLE
Error: Could not find or load main class org.goobs.naturalli.Client

### ISSUE THREAD

**Issue by p6jain** [gangeli/NaturalLI#14]
On running: ./run Evaluate src/org/goobs/truth/conf/conceptnet.conf
I get the following error:
Error: Could not find or load main class org.goobs.naturalli.Client

I have installed java-8-openjdk, scala  2.11.0 and using the latest CoreNLP project.

Not sure if relevant but on importing naturalli_schema/data/index into postgresql naturalli database, relation edge_type wasn't formed (details marked in previous issue).

Can you please help here.

On running: make java_test
I get the following error:
make -C src naturalli_client.jar
make[1]: Entering directory `/code/EMNLP_naturalli/NaturalLI-master/src'
Compiling (/usr/lib/jvm/java-8-openjdk-amd64/bin/javac)...
./org/goobs/naturalli/Props.java:3: error: package com.typesafe.config does not exist
import com.typesafe.config.Config;
                          ^
./org/goobs/naturalli/Props.java:4: error: package com.typesafe.config does not exist
import com.typesafe.config.ConfigFactory;
                          ^
./org/goobs/naturalli/Props.java:5: error: package com.typesafe.config does not exist
import com.typesafe.config.ConfigValue;
                          ^
./org/goobs/naturalli/Props.java:6: error: cannot find symbol
import edu.stanford.nlp.util.Execution;
                            ^
  symbol:   class Execution
  location: package edu.stanford.nlp.util
./org/goobs/naturalli/Props.java:7: error: package edu.stanford.nlp.util.Execution does not exist
import edu.stanford.nlp.util.Execution.Option;
                                      ^
./org/goobs/naturalli/Props.java:38: error: cannot find symbol
  @Option(name="psql.host", gloss="The hostname for the PSQL server")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:40: error: cannot find symbol
  @Option(name="psql.port", gloss="The port at which postgres is running")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:42: error: cannot find symbol
  @Option(name="psql.db", gloss="The database name")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:44: error: cannot find symbol
  @Option(name="psql.username", gloss="The username for the postgres session")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:46: error: cannot find symbol
  @Option(name="psql.password", gloss="The password for the postgres session")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:49: error: cannot find symbol
  @Option(name="natlog.indexer.lazy", gloss="If true, do word indexing lazily rather than reading the indexer at once")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:51: error: cannot find symbol
  @Option(name="natlog.indexer.replner", gloss="If true, replace unknown tokens with the NER tag they represent")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:54: error: cannot find symbol
  @Option(name="server.main.host", gloss="The hostname for the inference server")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:56: error: cannot find symbol
  @Option(name="server.main.port", gloss="The hostname for the inference server")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:58: error: cannot find symbol
  @Option(name="server.main.threads", gloss="The number of threads to run training on. This is primarily determined by the server capacity")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:60: error: cannot find symbol
  @Option(name="server.backup.do", gloss="The hostname for the inference server")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:62: error: cannot find symbol
  @Option(name="server.backup.discount", gloss="The hostname for the inference server")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:64: error: cannot find symbol
  @Option(name="server.backup.host", gloss="The hostname for the inference server")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:66: error: cannot find symbol
  @Option(name="server.backup.port", gloss="The hostname for the inference server")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:68: error: cannot find symbol
  @Option(name="server.backup.threads", gloss="The number of threads to run training on. This is primarily determined by the server capacity")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:71: error: cannot find symbol
  @Option(name="search.timeout", gloss="The maximum number of ticks to run for on the server")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:73: error: cannot find symbol
  @Option(name="search.allowlookup", gloss="Allow the search to return exact matches")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:76: error: cannot find symbol
  @Option(name="natlog.ollie.jar", gloss="The path to the Ollie *.jar file")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:78: error: cannot find symbol
  @Option(name="natlog.ollie.port", gloss="The port to start an Ollie server on")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:80: error: cannot find symbol
  @Option(name="natlog.ollie.malt.path", gloss="The path to the Malt parser serialized model")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:83: error: cannot find symbol
  @Option(name="data.fracas.path", gloss="The path to the FraCaS test suite")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:85: error: cannot find symbol
  @Option(name="data.ave.path", gloss="The paths to the AVE answer validation examples by year")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:91: error: cannot find symbol
  @Option(name="data.mturk.train", gloss="The path to the MTurk annotated ReVerb training examples")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:93: error: cannot find symbol
  @Option(name="data.mturk.test", gloss="The path to the MTurk annotated Reverb test examples")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:95: error: cannot find symbol
  @Option(name="data.conceptnet.path", gloss="The path to the ConceptNet positive examples")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:98: error: cannot find symbol
  @Option(name="learn.model.dir", gloss="The directory to look for models in")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:100: error: cannot find symbol
  @Option(name="learn.model.start", gloss="The start iteration to resume training from. This will be floored to the nearest 1k")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:102: error: cannot find symbol
  @Option(name="learn.train", gloss="The corpus to use for training")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:104: error: cannot find symbol
  @Option(name="learn.test", gloss="The corpus to use for testing")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:106: error: cannot find symbol
  @Option(name="learn.prCurve", gloss="The corpus to use for testing")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:108: error: cannot find symbol
  @Option(name="learn.online.iterations", gloss="The number of iterations to run learning for")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:110: error: cannot find symbol
  @Option(name="learn.online.sgd.nu", gloss="The regularization $nu$ for SGD")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:112: error: cannot find symbol
  @Option(name="learn.offline.passes", gloss="The number of passes through the data to make")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:114: error: cannot find symbol
  @Option(name="learn.offline.sigma", gloss="The regularization to apply for the logistic classifier (large is generally good)")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:116: error: cannot find symbol
  @Option(name="learn.initialization", gloss="The number of passes through the data to make")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:119: error: cannot find symbol
  @Option(name="evaluate.allowunk", gloss="Allow unknown as a state we are evaluating against")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:121: error: cannot find symbol
  @Option(name="evaluate.model", gloss="The model to load when evaluating")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:124: error: cannot find symbol
  @Option(name="script.wordnet.path", gloss="The path to the saved wordnet ontology (see sim.jar)")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:126: error: cannot find symbol
  @Option(name="script.distsim.cos", gloss="The path to the cosine similarity nearest neighbors")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:129: error: cannot find symbol
  @Option(name="script.reverb.raw.dir", gloss="The raw directory where Reverb outputs are stored")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:131: error: cannot find symbol
  @Option(name="script.reverb.raw.gzip", gloss="If true, the input files are in gzip format")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:133: error: cannot find symbol
  @Option(name="script.reverb.head.do", gloss="If true, compute the head word for each fact added")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:136: error: cannot find symbol
  @Option(name="script.freebase.raw.path", gloss="The location of the raw Freebase dump")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:138: error: cannot find symbol
  @Option(name="script.freebase.path", gloss="The location of the processed Freebase dump")
   ^
  symbol:   class Option
  location: class Props
./org/goobs/naturalli/Props.java:141: error: cannot find symbol
  @Option(name="demo.do", gloss="True if we are running from the web demo")
   ^
  symbol:   class Option
  location: class Props
/code/EMNLP_naturalli/NaturalLI-master/lib/corenlp-scala.jar(edu/stanford/nlp/Sentence.class): warning: Cannot find annotation method 'bytes()' in type 'ScalaSignature': class file for scala.reflect.ScalaSignature not found
./edu/stanford/nlp/natlog/GaborMono.java:320: error: cannot find symbol
        OUTER: for (int start = 0; start < Math.min(2, span.size() - 1); ++start) {
                                                           ^
  symbol:   method size()
  location: variable span of type Span
./edu/stanford/nlp/natlog/GaborMono.java:321: error: cannot find symbol
          for (int len = span.size() - start - 1; len > 0; --len) {
                             ^
  symbol:   method size()
  location: variable span of type Span
./edu/stanford/nlp/natlog/GaborMono.java:329: error: for-each not applicable to expression type
        for (int index : span) {
                         ^
  required: array or java.lang.Iterable
  found:    Span
./org/goobs/naturalli/Props.java:59: error: cannot find symbol
  public static int SERVER_MAIN_THREADS = Execution.threads;
                                          ^
  symbol:   variable Execution
  location: class Props
./org/goobs/naturalli/Props.java:69: error: cannot find symbol
  public static int SERVER_BACKUP_THREADS = Execution.threads;
                                            ^
  symbol:   variable Execution
  location: class Props
./org/goobs/naturalli/Props.java:151: error: cannot find symbol
    Execution.optionClasses = new Class<?>[stackTrace.length];
    ^
  symbol:   variable Execution
  location: class Props
./org/goobs/naturalli/Props.java:154: error: cannot find symbol
        Execution.optionClasses[i] = Class.forName(stackTrace[i].getClassName());
        ^
  symbol:   variable Execution
  location: class Props
./org/goobs/naturalli/Props.java:155: error: cannot find symbol
      } catch (ClassNotFoundException e) { logger.fatal(e); }
                                                 ^
  symbol:   method fatal(ClassNotFoundException)
  location: variable logger of type RedwoodChannels
./org/goobs/naturalli/Props.java:160: error: cannot find symbol
      if (!new File(args[0]).canRead()) logger.fatal("Cannot read typesafe-config file: " + args[0]);
                                              ^
  symbol:   method fatal(String)
  location: variable logger of type RedwoodChannels
./org/goobs/naturalli/Props.java:161: error: cannot find symbol
      Config config = null;
      ^
  symbol:   class Config
  location: class Props
./org/goobs/naturalli/Props.java:163: error: cannot find symbol
        config = ConfigFactory.parseFile(new File(args[0]).getCanonicalFile()).resolve();
                 ^
  symbol:   variable ConfigFactory
  location: class Props
./org/goobs/naturalli/Props.java:169: error: cannot find symbol
      for (Map.Entry<String, ConfigValue> entry : config.entrySet()) {
                             ^
  symbol:   class ConfigValue
  location: class Props
./org/goobs/naturalli/Props.java:175: error: cannot find symbol
      Execution.exec(new Runnable() { @Override public void run() {
      ^
  symbol:   variable Execution
  location: class Props
./org/goobs/naturalli/Props.java:182: error: cannot find symbol
      Execution.exec(new Runnable() { @Override public void run() {
      ^
  symbol:   variable Execution
  location: class Props
./org/goobs/naturalli/Quantifier.java:136: error: cannot access Seq
    this.surfaceForm = new Sentence(this.literalSurfaceForm).lemma();
                       ^
  class file for scala.collection.Seq not found
65 errors
1 warning
make[1]: *** [naturalli_client.jar] Error 1
make[1]: Leaving directory`/code/EMNLP_naturalli/NaturalLI-master/src'
make: **\* [src/naturalli_client.jar] Error 2

**Comment by gangeli** [comment]
Did you configure with --with-scala and --with-java? It looks like you're not finding the scala standard library, which is picked up from the --with-scala option (set to SCALA_HOME).

**Comment by p6jain** [comment]
Thanks Gabor!
On fixing the SCALA_HOME I got this error:
<error>
BUILD FAILED
/code/EMNLP_naturalli/NaturalLI-master/build.xml:40: /code/EMNLP_naturalli/NaturalLI-master/${env.JAVANLP_HOME}/projects/core/lib does not exist.
</error>
I updated buils.xml line number 22 from
<fileset dir="${env.JAVANLP_HOME}/projects/core/lib">
to
<fileset dir="lib">

This fixed the issue. Next I got the following error:
BUILD FAILED
/code/EMNLP_naturalli/NaturalLI-master/build.xml:40: taskdef A class needed by class org.scalatest.tools.ScalaTestAntTask cannot be found: scala/Function1
 using the classloader AntClassLoader[/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/lib/corenlp-caseless-models.jar:/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/lib/corenlp-models.jar:/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/lib/corenlp-scala.jar:/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/lib/corenlp.jar:/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/lib/jaws.jar:/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/lib/postgresql.jar:/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/lib/protobuf.jar:/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/lib/test/hamcrest-core-1.3.jar:/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/lib/test/junit-4.11.jar:/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/lib/test/scalatest_2.11-2.1.6.jar:/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/src/naturalli_client.jar:/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/test/src/test_client.jar]

I am not sure how to fix this. Can you please help here.

PS: I found some hardcoded paths in target name "war" in build.xml
      <lib dir="/u/nlp/data/StanfordCoreNLPModels/corenlp">
        <include name="stanford-corenlp-2014-07-02-models.jar"/>
      </lib>
      <lib dir="/u/nlp/data/StanfordCoreNLPModels/corenlp-caseless">
        <include name="stanford-corenlp-caseless-2014-02-25-models.jar"/>
      </lib>

**Comment by gangeli** [comment]
Is SCALA_HOME set globally? The error is that the scalatest ant plugin isn't loading properly.

If I recall, you only need this for the test program anyways though. Does the rest of the code build?

**Comment by p6jain** [comment]
Yes SCALA_HOME is set globally.

When I the following command:
./run Evaluate src/org/goobs/truth/conf/conceptnet.conf

I get this error:
valuate src/org/goobs/truth/conf/conceptnet.conf
running org.goobs.naturalli.Evaluate
using(src/org/goobs/naturalli/conf/base.conf)
-- 1 job submitted
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: edu/stanford/nlp/stats/Counter
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.stats.Counter
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

STEPS I followed:
1) ./autogen.sh
2)
./configure --with-protoc=/usr \
--enable-debug \
--with-postgresql=/usr/bin/pg_config \
--with-scala=/usr/share/scala \
--with-java=/usr/lib/jvm/java-8-openjdk-amd64 \
--with-corenlp=/code/EMNLP_naturalli/NaturalLI-master/lib/corenlp.jar \
--with-corenlp-models=/code/EMNLP_naturalli/NaturalLI-master/lib/corenlp-models.jar \
--with-corenlp-caseless-models=/code/EMNLP_naturalli/NaturalLI-master/lib/corenlp-caseless-models.jar \
--prefix=/usr/local/ \
CXX=g++ \
PGHOST=127.0.0.1  PGPORT=5432 \
DBNAME=naturalli PGUSER=postgres \
PGPASSWORD=XXXX \
GREEDY_LOAD=1

3) make
4) make install
5) src/naturalli_server
-----Everything works fine till here-----
6) ./run Evaluate src/org/goobs/truth/conf/conceptnet.conf
throws mentioned error

**Comment by p6jain** [comment]
1. What does JAVANLP_HOME store?
2. run in main folder has the following lines:
    System.getenv("JAVANLP_HOME") + "/projects/more/classes",
    System.getenv("JAVANLP_HOME") + "/projects/more/lib/BerkeleyParser.jar",
    System.getenv("JAVANLP_HOME") + "/projects/research/classes",
I can't find the folders as well as the jar specified in the project folder.

**Comment by gangeli** [comment]
Ah, yes. `JAVANLP_HOME` is the root of our internal codebase -- all instances of `JAVANLP_HOME/projects/core` can be replaced with the path to a checkout of CoreNLP (e.g., cloning https://github.com/stanfordnlp/CoreNLP). Hopefully, there's no need to include `more` and `research` -- if it doesn't compile let me know and I can try to migrate files into CoreNLP.

**Comment by p6jain** [comment]
Same error again.

**Comment by gangeli** [comment]
Can you print the value of `cp` in the run script? The error of not finding the Counter class is caused by java not picking up the CoreNLP classes in the classpath.

**Comment by p6jain** [comment]
Oh! yes CoreNLP classes are not picked up in the class path.
How should I add it?

List(Attributed(/code/EMNLP_naturalli/NaturalLI-master/target/scala-2.9.1/classes), Attributed(/code/EMNLP_naturalli/NaturalLI-master/lib/corenlp-scala.jar), Attributed(/code/EMNLP_naturalli/NaturalLI-master/lib/jaws.jar), Attributed(/code/EMNLP_naturalli/NaturalLI-master/lib/postgresql.jar), Attributed(/code/EMNLP_naturalli/NaturalLI-master/lib/protobuf.jar), Attributed(/code/EMNLP_naturalli/NaturalLI-master/lib/corenlp-models.jar), Attributed(/code/EMNLP_naturalli/NaturalLI-master/lib/corenlp-caseless-models.jar), Attributed(/code/EMNLP_naturalli/NaturalLI-master/lib/corenlp.jar), Attributed(/root/.sbt/boot/scala-2.9.1/lib/scala-library.jar))

**Comment by gangeli** [comment]
So, in the script the value of `val cp:String` should be the ':' delimited classpath string. You can take all the elements you mentioned and just join them on ':' and it should work?

**Comment by p6jain** [comment]
I added the path to CoreNLP folder and printed cp:
src/naturalli_client.jar:test/src/test_client.jar:/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/CoreNLP-master/li
b/joda-time.jar:/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/CoreNLP-master/lib/jollyday-0.4.7.jar:/analytics/pr
achi/code/EMNLP_naturalli/NaturalLI-master/CoreNLP-master/classes:/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/C
oreNLP-master/lib/BerkeleyParser.jar:/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/lib/reverb.jar:/analytics/prac
hi/code/EMNLP_naturalli/NaturalLI-master/lib/postgresql.jar:/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/lib/cor
enlp-models.jar:/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/lib/corenlp-caseless-models.jar:/analytics/prachi/c
ode/EMNLP_naturalli/NaturalLI-master/CoreNLP-master/classes:/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/CoreNLP
-master:/usr/share/scala/lib/scala-library.jar:/usr/share/scala/lib/config-1.2.0.jar:/usr/share/scala/lib/scala-xml_2.11-1.0.1.jar:lib/corenlp-scala.jar:lib/trove.jar:lib/jaws.jar:lib/scripts/sim-1.0.jar:lib/protobuf.jar

But when I use sbt command prompt to print class path, I get this:
show runtime:full-classpath
[info] List(Attributed(/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/target/scala-2.9.1/classes), Attributed(/ana
lytics/prachi/code/EMNLP_naturalli/NaturalLI-master/lib/corenlp-scala.jar), Attributed(/analytics/prachi/code/EMNLP_natural
li/NaturalLI-master/lib/jaws.jar), Attributed(/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/lib/postgresql.jar), 
Attributed(/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/lib/protobuf.jar), Attributed(/analytics/prachi/code/EMN
LP_naturalli/NaturalLI-master/lib/corenlp-models.jar), Attributed(/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/l
ib/corenlp-caseless-models.jar), Attributed(/analytics/prachi/code/EMNLP_naturalli/NaturalLI-master/lib/corenlp.jar), Attributed(/root/.sbt/boot/scala-2.9.1/lib/scala-library.jar))

notice the path to CORENLP is not here.

And I am still getting the same error.

Any idea, how to fix things?

**Comment by gangeli** [comment]
I'm not sure -- I tend to avoid sbt like the plague, for exactly these kinds of reasons. You need to somehow include the CoreNLP libraries in the sbt build.
