### ISSUE TITLE
could not download data files from dropbox 

### ISSUE THREAD

**Issue by rudaoshi** [gangeli/NaturalLI#17]
The download links are invalid. Please upload these files to github.

**Comment by gangeli** [comment]
Huh; Dropbox seems to have suspended my account due to inactivity. I'm hesitant putting these on GitHub, as they're fairly large. I'll try to reinstate my account, and perhaps move the files to S3 or somewhere else that doesn't delete data on a whim.

**Comment by lenny-t** [comment]
@gangeli any update on the data files? interested in playing around with this :)

**Comment by Muuo** [comment]
@gangeli I'm willing to host the data file if you like

**Comment by gangeli** [comment]
I guess maybe easiest is if I just commit them to Git, and let people deal with the large download. The commit should be showing up soon. I haven't actually tested that it works from a clean install though, so send bugs if you find them!

**Comment by Muuo** [comment]
@gangeli Thanks! If the file size exceeds 100MB you may want to consider using Git LFS (https://help.github.com/articles/versioning-large-files/).
